/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademicoRouteImport } from './routes/academico'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as AsignaturasRouteImport } from './routes/asignaturas'
import { Route as AsistenciaRouteImport } from './routes/asistencia'
import { Route as BloquesRouteImport } from './routes/bloques'
import { Route as CalificacionesRouteImport } from './routes/calificaciones'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as ConflictosRouteImport } from './routes/conflictos'
import { Route as ContratosRouteImport } from './routes/contratos'
import { Route as CursosRouteImport } from './routes/cursos'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DireccionRouteImport } from './routes/direccion'
import { Route as DocentesRouteImport } from './routes/docentes'
import { Route as EspaciosRouteImport } from './routes/espacios'
import { Route as EstadisticasRouteImport } from './routes/estadisticas'
import { Route as EstudiantesRouteImport } from './routes/estudiantes'
import { Route as HorariosRouteImport } from './routes/horarios'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as IntranetRouteImport } from './routes/intranet'
import { Route as LibroClasesRouteImport } from './routes/libro-clases'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MatriculaRouteImport } from './routes/matricula'
import { Route as MiHorarioRouteImport } from './routes/mi-horario'
import { Route as MisClasesRouteImport } from './routes/mis-clases'
import { Route as MisCursosRouteImport } from './routes/mis-cursos'
import { Route as MisResumenAcademicoRouteImport } from './routes/mis-resumen-academico'
import { Route as MisResumenesRouteImport } from './routes/mis-resumenes'
import { Route as PieRouteImport } from './routes/pie'
import { Route as PlanificacionesRouteImport } from './routes/planificaciones'
import { Route as RecursosRouteImport } from './routes/recursos'
import { Route as ReemplazosRouteImport } from './routes/reemplazos'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as AdminAuditoriaRouteImport } from './routes/admin.auditoria'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as CurriculumCoberturaRouteImport } from './routes/curriculum.cobertura'
import { Route as CurriculumUnidadesRouteImport } from './routes/curriculum.unidades'
import { Route as EstudiantesIdRouteImport } from './routes/estudiantes.$id'
import { Route as InspectoriaIndexRouteImport } from './routes/inspectoria.index'
import { Route as InspectoriaAtrasosRouteImport } from './routes/inspectoria.atrasos'
import { Route as InspectoriaConvivenciaRouteImport } from './routes/inspectoria.convivencia'
import { Route as InvitacionTokenRouteImport } from './routes/invitacion.$token'
import { Route as MatriculaIdRouteImport } from './routes/matricula.$id'
import { Route as SuperadminIdRouteImport } from './routes/superadmin.$id'
import { Route as CSlugLoginRouteImport } from './routes/c.$slug.login'
import { Route as CSlugMatriculaRouteImport } from './routes/c.$slug.matricula'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicoRoute = AcademicoRouteImport.update({
  id: '/academico',
  path: '/academico',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const AsignaturasRoute = AsignaturasRouteImport.update({
  id: '/asignaturas',
  path: '/asignaturas',
  getParentRoute: () => rootRouteImport,
} as any)
const AsistenciaRoute = AsistenciaRouteImport.update({
  id: '/asistencia',
  path: '/asistencia',
  getParentRoute: () => rootRouteImport,
} as any)
const BloquesRoute = BloquesRouteImport.update({
  id: '/bloques',
  path: '/bloques',
  getParentRoute: () => rootRouteImport,
} as any)
const CalificacionesRoute = CalificacionesRouteImport.update({
  id: '/calificaciones',
  path: '/calificaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const ConflictosRoute = ConflictosRouteImport.update({
  id: '/conflictos',
  path: '/conflictos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosRoute = ContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosRoute = CursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DireccionRoute = DireccionRouteImport.update({
  id: '/direccion',
  path: '/direccion',
  getParentRoute: () => rootRouteImport,
} as any)
const DocentesRoute = DocentesRouteImport.update({
  id: '/docentes',
  path: '/docentes',
  getParentRoute: () => rootRouteImport,
} as any)
const EspaciosRoute = EspaciosRouteImport.update({
  id: '/espacios',
  path: '/espacios',
  getParentRoute: () => rootRouteImport,
} as any)
const EstadisticasRoute = EstadisticasRouteImport.update({
  id: '/estadisticas',
  path: '/estadisticas',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudiantesRoute = EstudiantesRouteImport.update({
  id: '/estudiantes',
  path: '/estudiantes',
  getParentRoute: () => rootRouteImport,
} as any)
const HorariosRoute = HorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const IntranetRoute = IntranetRouteImport.update({
  id: '/intranet',
  path: '/intranet',
  getParentRoute: () => rootRouteImport,
} as any)
const LibroClasesRoute = LibroClasesRouteImport.update({
  id: '/libro-clases',
  path: '/libro-clases',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MatriculaRoute = MatriculaRouteImport.update({
  id: '/matricula',
  path: '/matricula',
  getParentRoute: () => rootRouteImport,
} as any)
const MiHorarioRoute = MiHorarioRouteImport.update({
  id: '/mi-horario',
  path: '/mi-horario',
  getParentRoute: () => rootRouteImport,
} as any)
const MisClasesRoute = MisClasesRouteImport.update({
  id: '/mis-clases',
  path: '/mis-clases',
  getParentRoute: () => rootRouteImport,
} as any)
const MisCursosRoute = MisCursosRouteImport.update({
  id: '/mis-cursos',
  path: '/mis-cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const MisResumenAcademicoRoute = MisResumenAcademicoRouteImport.update({
  id: '/mis-resumen-academico',
  path: '/mis-resumen-academico',
  getParentRoute: () => rootRouteImport,
} as any)
const MisResumenesRoute = MisResumenesRouteImport.update({
  id: '/mis-resumenes',
  path: '/mis-resumenes',
  getParentRoute: () => rootRouteImport,
} as any)
const PieRoute = PieRouteImport.update({
  id: '/pie',
  path: '/pie',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanificacionesRoute = PlanificacionesRouteImport.update({
  id: '/planificaciones',
  path: '/planificaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosRoute = RecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => rootRouteImport,
} as any)
const ReemplazosRoute = ReemplazosRouteImport.update({
  id: '/reemplazos',
  path: '/reemplazos',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/admin/auditoria',
  path: '/admin/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumCoberturaRoute = CurriculumCoberturaRouteImport.update({
  id: '/curriculum/cobertura',
  path: '/curriculum/cobertura',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumUnidadesRoute = CurriculumUnidadesRouteImport.update({
  id: '/curriculum/unidades',
  path: '/curriculum/unidades',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudiantesIdRoute = EstudiantesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EstudiantesRoute,
} as any)
const InspectoriaIndexRoute = InspectoriaIndexRouteImport.update({
  id: '/inspectoria/',
  path: '/inspectoria/',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectoriaAtrasosRoute = InspectoriaAtrasosRouteImport.update({
  id: '/inspectoria/atrasos',
  path: '/inspectoria/atrasos',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectoriaConvivenciaRoute = InspectoriaConvivenciaRouteImport.update({
  id: '/inspectoria/convivencia',
  path: '/inspectoria/convivencia',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitacionTokenRoute = InvitacionTokenRouteImport.update({
  id: '/invitacion/$token',
  path: '/invitacion/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MatriculaIdRoute = MatriculaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MatriculaRoute,
} as any)
const SuperadminIdRoute = SuperadminIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SuperadminRoute,
} as any)
const CSlugLoginRoute = CSlugLoginRouteImport.update({
  id: '/c/$slug/login',
  path: '/c/$slug/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugMatriculaRoute = CSlugMatriculaRouteImport.update({
  id: '/c/$slug/matricula',
  path: '/c/$slug/matricula',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academico': typeof AcademicoRoute
  '/ajustes': typeof AjustesRoute
  '/asignaturas': typeof AsignaturasRoute
  '/asistencia': typeof AsistenciaRoute
  '/bloques': typeof BloquesRoute
  '/calificaciones': typeof CalificacionesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/conflictos': typeof ConflictosRoute
  '/contratos': typeof ContratosRoute
  '/cursos': typeof CursosRoute
  '/dashboard': typeof DashboardRoute
  '/direccion': typeof DireccionRoute
  '/docentes': typeof DocentesRoute
  '/espacios': typeof EspaciosRoute
  '/estadisticas': typeof EstadisticasRoute
  '/estudiantes': typeof EstudiantesRouteWithChildren
  '/horarios': typeof HorariosRoute
  '/importar': typeof ImportarRoute
  '/intranet': typeof IntranetRoute
  '/libro-clases': typeof LibroClasesRoute
  '/login': typeof LoginRoute
  '/matricula': typeof MatriculaRouteWithChildren
  '/mi-horario': typeof MiHorarioRoute
  '/mis-clases': typeof MisClasesRoute
  '/mis-cursos': typeof MisCursosRoute
  '/mis-resumen-academico': typeof MisResumenAcademicoRoute
  '/mis-resumenes': typeof MisResumenesRoute
  '/pie': typeof PieRoute
  '/planificaciones': typeof PlanificacionesRoute
  '/recursos': typeof RecursosRoute
  '/reemplazos': typeof ReemplazosRoute
  '/register': typeof RegisterRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/login': typeof AdminLoginRoute
  '/curriculum/cobertura': typeof CurriculumCoberturaRoute
  '/curriculum/unidades': typeof CurriculumUnidadesRoute
  '/estudiantes/$id': typeof EstudiantesIdRoute
  '/inspectoria/atrasos': typeof InspectoriaAtrasosRoute
  '/inspectoria/convivencia': typeof InspectoriaConvivenciaRoute
  '/invitacion/$token': typeof InvitacionTokenRoute
  '/matricula/$id': typeof MatriculaIdRoute
  '/superadmin/$id': typeof SuperadminIdRoute
  '/inspectoria/': typeof InspectoriaIndexRoute
  '/c/$slug/login': typeof CSlugLoginRoute
  '/c/$slug/matricula': typeof CSlugMatriculaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academico': typeof AcademicoRoute
  '/ajustes': typeof AjustesRoute
  '/asignaturas': typeof AsignaturasRoute
  '/asistencia': typeof AsistenciaRoute
  '/bloques': typeof BloquesRoute
  '/calificaciones': typeof CalificacionesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/conflictos': typeof ConflictosRoute
  '/contratos': typeof ContratosRoute
  '/cursos': typeof CursosRoute
  '/dashboard': typeof DashboardRoute
  '/direccion': typeof DireccionRoute
  '/docentes': typeof DocentesRoute
  '/espacios': typeof EspaciosRoute
  '/estadisticas': typeof EstadisticasRoute
  '/estudiantes': typeof EstudiantesRouteWithChildren
  '/horarios': typeof HorariosRoute
  '/importar': typeof ImportarRoute
  '/intranet': typeof IntranetRoute
  '/libro-clases': typeof LibroClasesRoute
  '/login': typeof LoginRoute
  '/matricula': typeof MatriculaRouteWithChildren
  '/mi-horario': typeof MiHorarioRoute
  '/mis-clases': typeof MisClasesRoute
  '/mis-cursos': typeof MisCursosRoute
  '/mis-resumen-academico': typeof MisResumenAcademicoRoute
  '/mis-resumenes': typeof MisResumenesRoute
  '/pie': typeof PieRoute
  '/planificaciones': typeof PlanificacionesRoute
  '/recursos': typeof RecursosRoute
  '/reemplazos': typeof ReemplazosRoute
  '/register': typeof RegisterRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/login': typeof AdminLoginRoute
  '/curriculum/cobertura': typeof CurriculumCoberturaRoute
  '/curriculum/unidades': typeof CurriculumUnidadesRoute
  '/estudiantes/$id': typeof EstudiantesIdRoute
  '/inspectoria/atrasos': typeof InspectoriaAtrasosRoute
  '/inspectoria/convivencia': typeof InspectoriaConvivenciaRoute
  '/invitacion/$token': typeof InvitacionTokenRoute
  '/matricula/$id': typeof MatriculaIdRoute
  '/superadmin/$id': typeof SuperadminIdRoute
  '/inspectoria': typeof InspectoriaIndexRoute
  '/c/$slug/login': typeof CSlugLoginRoute
  '/c/$slug/matricula': typeof CSlugMatriculaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academico': typeof AcademicoRoute
  '/ajustes': typeof AjustesRoute
  '/asignaturas': typeof AsignaturasRoute
  '/asistencia': typeof AsistenciaRoute
  '/bloques': typeof BloquesRoute
  '/calificaciones': typeof CalificacionesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/conflictos': typeof ConflictosRoute
  '/contratos': typeof ContratosRoute
  '/cursos': typeof CursosRoute
  '/dashboard': typeof DashboardRoute
  '/direccion': typeof DireccionRoute
  '/docentes': typeof DocentesRoute
  '/espacios': typeof EspaciosRoute
  '/estadisticas': typeof EstadisticasRoute
  '/estudiantes': typeof EstudiantesRouteWithChildren
  '/horarios': typeof HorariosRoute
  '/importar': typeof ImportarRoute
  '/intranet': typeof IntranetRoute
  '/libro-clases': typeof LibroClasesRoute
  '/login': typeof LoginRoute
  '/matricula': typeof MatriculaRouteWithChildren
  '/mi-horario': typeof MiHorarioRoute
  '/mis-clases': typeof MisClasesRoute
  '/mis-cursos': typeof MisCursosRoute
  '/mis-resumen-academico': typeof MisResumenAcademicoRoute
  '/mis-resumenes': typeof MisResumenesRoute
  '/pie': typeof PieRoute
  '/planificaciones': typeof PlanificacionesRoute
  '/recursos': typeof RecursosRoute
  '/reemplazos': typeof ReemplazosRoute
  '/register': typeof RegisterRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/login': typeof AdminLoginRoute
  '/curriculum/cobertura': typeof CurriculumCoberturaRoute
  '/curriculum/unidades': typeof CurriculumUnidadesRoute
  '/estudiantes/$id': typeof EstudiantesIdRoute
  '/inspectoria/atrasos': typeof InspectoriaAtrasosRoute
  '/inspectoria/convivencia': typeof InspectoriaConvivenciaRoute
  '/invitacion/$token': typeof InvitacionTokenRoute
  '/matricula/$id': typeof MatriculaIdRoute
  '/superadmin/$id': typeof SuperadminIdRoute
  '/inspectoria/': typeof InspectoriaIndexRoute
  '/c/$slug/login': typeof CSlugLoginRoute
  '/c/$slug/matricula': typeof CSlugMatriculaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academico'
    | '/ajustes'
    | '/asignaturas'
    | '/asistencia'
    | '/bloques'
    | '/calificaciones'
    | '/configuracion'
    | '/conflictos'
    | '/contratos'
    | '/cursos'
    | '/dashboard'
    | '/direccion'
    | '/docentes'
    | '/espacios'
    | '/estadisticas'
    | '/estudiantes'
    | '/horarios'
    | '/importar'
    | '/intranet'
    | '/libro-clases'
    | '/login'
    | '/matricula'
    | '/mi-horario'
    | '/mis-clases'
    | '/mis-cursos'
    | '/mis-resumen-academico'
    | '/mis-resumenes'
    | '/pie'
    | '/planificaciones'
    | '/recursos'
    | '/reemplazos'
    | '/register'
    | '/superadmin'
    | '/admin/auditoria'
    | '/admin/login'
    | '/curriculum/cobertura'
    | '/curriculum/unidades'
    | '/estudiantes/$id'
    | '/inspectoria/atrasos'
    | '/inspectoria/convivencia'
    | '/invitacion/$token'
    | '/matricula/$id'
    | '/superadmin/$id'
    | '/inspectoria/'
    | '/c/$slug/login'
    | '/c/$slug/matricula'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academico'
    | '/ajustes'
    | '/asignaturas'
    | '/asistencia'
    | '/bloques'
    | '/calificaciones'
    | '/configuracion'
    | '/conflictos'
    | '/contratos'
    | '/cursos'
    | '/dashboard'
    | '/direccion'
    | '/docentes'
    | '/espacios'
    | '/estadisticas'
    | '/estudiantes'
    | '/horarios'
    | '/importar'
    | '/intranet'
    | '/libro-clases'
    | '/login'
    | '/matricula'
    | '/mi-horario'
    | '/mis-clases'
    | '/mis-cursos'
    | '/mis-resumen-academico'
    | '/mis-resumenes'
    | '/pie'
    | '/planificaciones'
    | '/recursos'
    | '/reemplazos'
    | '/register'
    | '/superadmin'
    | '/admin/auditoria'
    | '/admin/login'
    | '/curriculum/cobertura'
    | '/curriculum/unidades'
    | '/estudiantes/$id'
    | '/inspectoria/atrasos'
    | '/inspectoria/convivencia'
    | '/invitacion/$token'
    | '/matricula/$id'
    | '/superadmin/$id'
    | '/inspectoria'
    | '/c/$slug/login'
    | '/c/$slug/matricula'
  id:
    | '__root__'
    | '/'
    | '/academico'
    | '/ajustes'
    | '/asignaturas'
    | '/asistencia'
    | '/bloques'
    | '/calificaciones'
    | '/configuracion'
    | '/conflictos'
    | '/contratos'
    | '/cursos'
    | '/dashboard'
    | '/direccion'
    | '/docentes'
    | '/espacios'
    | '/estadisticas'
    | '/estudiantes'
    | '/horarios'
    | '/importar'
    | '/intranet'
    | '/libro-clases'
    | '/login'
    | '/matricula'
    | '/mi-horario'
    | '/mis-clases'
    | '/mis-cursos'
    | '/mis-resumen-academico'
    | '/mis-resumenes'
    | '/pie'
    | '/planificaciones'
    | '/recursos'
    | '/reemplazos'
    | '/register'
    | '/superadmin'
    | '/admin/auditoria'
    | '/admin/login'
    | '/curriculum/cobertura'
    | '/curriculum/unidades'
    | '/estudiantes/$id'
    | '/inspectoria/atrasos'
    | '/inspectoria/convivencia'
    | '/invitacion/$token'
    | '/matricula/$id'
    | '/superadmin/$id'
    | '/inspectoria/'
    | '/c/$slug/login'
    | '/c/$slug/matricula'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademicoRoute: typeof AcademicoRoute
  AjustesRoute: typeof AjustesRoute
  AsignaturasRoute: typeof AsignaturasRoute
  AsistenciaRoute: typeof AsistenciaRoute
  BloquesRoute: typeof BloquesRoute
  CalificacionesRoute: typeof CalificacionesRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  ConflictosRoute: typeof ConflictosRoute
  ContratosRoute: typeof ContratosRoute
  CursosRoute: typeof CursosRoute
  DashboardRoute: typeof DashboardRoute
  DireccionRoute: typeof DireccionRoute
  DocentesRoute: typeof DocentesRoute
  EspaciosRoute: typeof EspaciosRoute
  EstadisticasRoute: typeof EstadisticasRoute
  EstudiantesRoute: typeof EstudiantesRouteWithChildren
  HorariosRoute: typeof HorariosRoute
  ImportarRoute: typeof ImportarRoute
  IntranetRoute: typeof IntranetRoute
  LibroClasesRoute: typeof LibroClasesRoute
  LoginRoute: typeof LoginRoute
  MatriculaRoute: typeof MatriculaRouteWithChildren
  MiHorarioRoute: typeof MiHorarioRoute
  MisClasesRoute: typeof MisClasesRoute
  MisCursosRoute: typeof MisCursosRoute
  MisResumenAcademicoRoute: typeof MisResumenAcademicoRoute
  MisResumenesRoute: typeof MisResumenesRoute
  PieRoute: typeof PieRoute
  PlanificacionesRoute: typeof PlanificacionesRoute
  RecursosRoute: typeof RecursosRoute
  ReemplazosRoute: typeof ReemplazosRoute
  RegisterRoute: typeof RegisterRoute
  SuperadminRoute: typeof SuperadminRouteWithChildren
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminLoginRoute: typeof AdminLoginRoute
  CurriculumCoberturaRoute: typeof CurriculumCoberturaRoute
  CurriculumUnidadesRoute: typeof CurriculumUnidadesRoute
  InspectoriaAtrasosRoute: typeof InspectoriaAtrasosRoute
  InspectoriaConvivenciaRoute: typeof InspectoriaConvivenciaRoute
  InvitacionTokenRoute: typeof InvitacionTokenRoute
  InspectoriaIndexRoute: typeof InspectoriaIndexRoute
  CSlugLoginRoute: typeof CSlugLoginRoute
  CSlugMatriculaRoute: typeof CSlugMatriculaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academico': {
      id: '/academico'
      path: '/academico'
      fullPath: '/academico'
      preLoaderRoute: typeof AcademicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asignaturas': {
      id: '/asignaturas'
      path: '/asignaturas'
      fullPath: '/asignaturas'
      preLoaderRoute: typeof AsignaturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asistencia': {
      id: '/asistencia'
      path: '/asistencia'
      fullPath: '/asistencia'
      preLoaderRoute: typeof AsistenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bloques': {
      id: '/bloques'
      path: '/bloques'
      fullPath: '/bloques'
      preLoaderRoute: typeof BloquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calificaciones': {
      id: '/calificaciones'
      path: '/calificaciones'
      fullPath: '/calificaciones'
      preLoaderRoute: typeof CalificacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conflictos': {
      id: '/conflictos'
      path: '/conflictos'
      fullPath: '/conflictos'
      preLoaderRoute: typeof ConflictosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos': {
      id: '/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof ContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos': {
      id: '/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof CursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direccion': {
      id: '/direccion'
      path: '/direccion'
      fullPath: '/direccion'
      preLoaderRoute: typeof DireccionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docentes': {
      id: '/docentes'
      path: '/docentes'
      fullPath: '/docentes'
      preLoaderRoute: typeof DocentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espacios': {
      id: '/espacios'
      path: '/espacios'
      fullPath: '/espacios'
      preLoaderRoute: typeof EspaciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estadisticas': {
      id: '/estadisticas'
      path: '/estadisticas'
      fullPath: '/estadisticas'
      preLoaderRoute: typeof EstadisticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudiantes': {
      id: '/estudiantes'
      path: '/estudiantes'
      fullPath: '/estudiantes'
      preLoaderRoute: typeof EstudiantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horarios': {
      id: '/horarios'
      path: '/horarios'
      fullPath: '/horarios'
      preLoaderRoute: typeof HorariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intranet': {
      id: '/intranet'
      path: '/intranet'
      fullPath: '/intranet'
      preLoaderRoute: typeof IntranetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libro-clases': {
      id: '/libro-clases'
      path: '/libro-clases'
      fullPath: '/libro-clases'
      preLoaderRoute: typeof LibroClasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matricula': {
      id: '/matricula'
      path: '/matricula'
      fullPath: '/matricula'
      preLoaderRoute: typeof MatriculaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-horario': {
      id: '/mi-horario'
      path: '/mi-horario'
      fullPath: '/mi-horario'
      preLoaderRoute: typeof MiHorarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-clases': {
      id: '/mis-clases'
      path: '/mis-clases'
      fullPath: '/mis-clases'
      preLoaderRoute: typeof MisClasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-cursos': {
      id: '/mis-cursos'
      path: '/mis-cursos'
      fullPath: '/mis-cursos'
      preLoaderRoute: typeof MisCursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-resumen-academico': {
      id: '/mis-resumen-academico'
      path: '/mis-resumen-academico'
      fullPath: '/mis-resumen-academico'
      preLoaderRoute: typeof MisResumenAcademicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-resumenes': {
      id: '/mis-resumenes'
      path: '/mis-resumenes'
      fullPath: '/mis-resumenes'
      preLoaderRoute: typeof MisResumenesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pie': {
      id: '/pie'
      path: '/pie'
      fullPath: '/pie'
      preLoaderRoute: typeof PieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planificaciones': {
      id: '/planificaciones'
      path: '/planificaciones'
      fullPath: '/planificaciones'
      preLoaderRoute: typeof PlanificacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos': {
      id: '/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof RecursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reemplazos': {
      id: '/reemplazos'
      path: '/reemplazos'
      fullPath: '/reemplazos'
      preLoaderRoute: typeof ReemplazosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/admin/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum/cobertura': {
      id: '/curriculum/cobertura'
      path: '/curriculum/cobertura'
      fullPath: '/curriculum/cobertura'
      preLoaderRoute: typeof CurriculumCoberturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum/unidades': {
      id: '/curriculum/unidades'
      path: '/curriculum/unidades'
      fullPath: '/curriculum/unidades'
      preLoaderRoute: typeof CurriculumUnidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudiantes/$id': {
      id: '/estudiantes/$id'
      path: '/$id'
      fullPath: '/estudiantes/$id'
      preLoaderRoute: typeof EstudiantesIdRouteImport
      parentRoute: typeof EstudiantesRoute
    }
    '/inspectoria/': {
      id: '/inspectoria/'
      path: '/inspectoria'
      fullPath: '/inspectoria/'
      preLoaderRoute: typeof InspectoriaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspectoria/atrasos': {
      id: '/inspectoria/atrasos'
      path: '/inspectoria/atrasos'
      fullPath: '/inspectoria/atrasos'
      preLoaderRoute: typeof InspectoriaAtrasosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspectoria/convivencia': {
      id: '/inspectoria/convivencia'
      path: '/inspectoria/convivencia'
      fullPath: '/inspectoria/convivencia'
      preLoaderRoute: typeof InspectoriaConvivenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitacion/$token': {
      id: '/invitacion/$token'
      path: '/invitacion/$token'
      fullPath: '/invitacion/$token'
      preLoaderRoute: typeof InvitacionTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matricula/$id': {
      id: '/matricula/$id'
      path: '/$id'
      fullPath: '/matricula/$id'
      preLoaderRoute: typeof MatriculaIdRouteImport
      parentRoute: typeof MatriculaRoute
    }
    '/superadmin/$id': {
      id: '/superadmin/$id'
      path: '/$id'
      fullPath: '/superadmin/$id'
      preLoaderRoute: typeof SuperadminIdRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/c/$slug/login': {
      id: '/c/$slug/login'
      path: '/c/$slug/login'
      fullPath: '/c/$slug/login'
      preLoaderRoute: typeof CSlugLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug/matricula': {
      id: '/c/$slug/matricula'
      path: '/c/$slug/matricula'
      fullPath: '/c/$slug/matricula'
      preLoaderRoute: typeof CSlugMatriculaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EstudiantesRouteChildren {
  EstudiantesIdRoute: typeof EstudiantesIdRoute
}

const EstudiantesRouteChildren: EstudiantesRouteChildren = {
  EstudiantesIdRoute: EstudiantesIdRoute,
}

const EstudiantesRouteWithChildren = EstudiantesRoute._addFileChildren(
  EstudiantesRouteChildren,
)

interface MatriculaRouteChildren {
  MatriculaIdRoute: typeof MatriculaIdRoute
}

const MatriculaRouteChildren: MatriculaRouteChildren = {
  MatriculaIdRoute: MatriculaIdRoute,
}

const MatriculaRouteWithChildren = MatriculaRoute._addFileChildren(
  MatriculaRouteChildren,
)

interface SuperadminRouteChildren {
  SuperadminIdRoute: typeof SuperadminIdRoute
}

const SuperadminRouteChildren: SuperadminRouteChildren = {
  SuperadminIdRoute: SuperadminIdRoute,
}

const SuperadminRouteWithChildren = SuperadminRoute._addFileChildren(
  SuperadminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademicoRoute: AcademicoRoute,
  AjustesRoute: AjustesRoute,
  AsignaturasRoute: AsignaturasRoute,
  AsistenciaRoute: AsistenciaRoute,
  BloquesRoute: BloquesRoute,
  CalificacionesRoute: CalificacionesRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  ConflictosRoute: ConflictosRoute,
  ContratosRoute: ContratosRoute,
  CursosRoute: CursosRoute,
  DashboardRoute: DashboardRoute,
  DireccionRoute: DireccionRoute,
  DocentesRoute: DocentesRoute,
  EspaciosRoute: EspaciosRoute,
  EstadisticasRoute: EstadisticasRoute,
  EstudiantesRoute: EstudiantesRouteWithChildren,
  HorariosRoute: HorariosRoute,
  ImportarRoute: ImportarRoute,
  IntranetRoute: IntranetRoute,
  LibroClasesRoute: LibroClasesRoute,
  LoginRoute: LoginRoute,
  MatriculaRoute: MatriculaRouteWithChildren,
  MiHorarioRoute: MiHorarioRoute,
  MisClasesRoute: MisClasesRoute,
  MisCursosRoute: MisCursosRoute,
  MisResumenAcademicoRoute: MisResumenAcademicoRoute,
  MisResumenesRoute: MisResumenesRoute,
  PieRoute: PieRoute,
  PlanificacionesRoute: PlanificacionesRoute,
  RecursosRoute: RecursosRoute,
  ReemplazosRoute: ReemplazosRoute,
  RegisterRoute: RegisterRoute,
  SuperadminRoute: SuperadminRouteWithChildren,
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminLoginRoute: AdminLoginRoute,
  CurriculumCoberturaRoute: CurriculumCoberturaRoute,
  CurriculumUnidadesRoute: CurriculumUnidadesRoute,
  InspectoriaAtrasosRoute: InspectoriaAtrasosRoute,
  InspectoriaConvivenciaRoute: InspectoriaConvivenciaRoute,
  InvitacionTokenRoute: InvitacionTokenRoute,
  InspectoriaIndexRoute: InspectoriaIndexRoute,
  CSlugLoginRoute: CSlugLoginRoute,
  CSlugMatriculaRoute: CSlugMatriculaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
